<?php
include('echo.php');
include('echo.php');
include('echo.php');
include('echo.php');
include('echo.php');
include('echo.php');
include('echo.php');
include_once('echo.php');
include_once('echo.php');
include_once('echo.php');
include_once('echo.php');
